myFile = open("task1.txt", "r").read()
print(myFile)
listOfCities = myFile.split('\n')
listOfCities.pop()
print(listOfCities)
listOfCities.append("Newcastle")
print(listOfCities)
print(listOfCities[0])
listOfCities.remove("Sunderland")
print(listOfCities)
